version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    networks:
      - my_bridge_network
    ports:
      - "3306:3306"
    volumes:
      - ./mysql-data:/var/lib/mysql
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend_spring
    environment:
      DATABASE_URL: jdbc:mysql://mysql:3306/devdb
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
      JWT_SECRET: ${JWT_SECRET}
    volumes:
      - ./src:/app/src
    ports:
      - "8080:8080"
    networks:
      - my_bridge_network

networks:
  my_bridge_network:
    driver: bridge
